import React from "react";
import { View, Image, Text, StyleSheet } from "react-native";

interface IllustrationImageProps {
  file?: string;
  style?: object;
  imageStyle?: object;
}

// Static map for Metro bundler static analysis
const imageMap: Record<string, ReturnType<typeof require>> = {
  "menkyogentsuki_1001.png": require("../assets/images/menkyogentsuki_1001.png"),
  "menkyogentsuki_1004.png": require("../assets/images/menkyogentsuki_1004.png"),
  "menkyogentsuki_1007.png": require("../assets/images/menkyogentsuki_1007.png"),
  "menkyogentsuki_101.png": require("../assets/images/menkyogentsuki_101.png"),
  "menkyogentsuki_1010.png": require("../assets/images/menkyogentsuki_1010.png"),
  "menkyogentsuki_1013.png": require("../assets/images/menkyogentsuki_1013.png"),
  "menkyogentsuki_1016.png": require("../assets/images/menkyogentsuki_1016.png"),
  "menkyogentsuki_1019.png": require("../assets/images/menkyogentsuki_1019.png"),
  "menkyogentsuki_1022.png": require("../assets/images/menkyogentsuki_1022.png"),
  "menkyogentsuki_1025.png": require("../assets/images/menkyogentsuki_1025.png"),
  "menkyogentsuki_1028.png": require("../assets/images/menkyogentsuki_1028.png"),
  "menkyogentsuki_1031.png": require("../assets/images/menkyogentsuki_1031.png"),
  "menkyogentsuki_1034.png": require("../assets/images/menkyogentsuki_1034.png"),
  "menkyogentsuki_1037.png": require("../assets/images/menkyogentsuki_1037.png"),
  "menkyogentsuki_104.png": require("../assets/images/menkyogentsuki_104.png"),
  "menkyogentsuki_1040.png": require("../assets/images/menkyogentsuki_1040.png"),
  "menkyogentsuki_1043.png": require("../assets/images/menkyogentsuki_1043.png"),
  "menkyogentsuki_1046.png": require("../assets/images/menkyogentsuki_1046.png"),
  "menkyogentsuki_1049.png": require("../assets/images/menkyogentsuki_1049.png"),
  "menkyogentsuki_105.png": require("../assets/images/menkyogentsuki_105.png"),
  "menkyogentsuki_1052.png": require("../assets/images/menkyogentsuki_1052.png"),
  "menkyogentsuki_1055.png": require("../assets/images/menkyogentsuki_1055.png"),
  "menkyogentsuki_1058.png": require("../assets/images/menkyogentsuki_1058.png"),
  "menkyogentsuki_1061.png": require("../assets/images/menkyogentsuki_1061.png"),
  "menkyogentsuki_1064.png": require("../assets/images/menkyogentsuki_1064.png"),
  "menkyogentsuki_1067.png": require("../assets/images/menkyogentsuki_1067.png"),
  "menkyogentsuki_1070.png": require("../assets/images/menkyogentsuki_1070.png"),
  "menkyogentsuki_1073.png": require("../assets/images/menkyogentsuki_1073.png"),
  "menkyogentsuki_1076.png": require("../assets/images/menkyogentsuki_1076.png"),
  "menkyogentsuki_1079.png": require("../assets/images/menkyogentsuki_1079.png"),
  "menkyogentsuki_1082.png": require("../assets/images/menkyogentsuki_1082.png"),
  "menkyogentsuki_1085.png": require("../assets/images/menkyogentsuki_1085.png"),
  "menkyogentsuki_1088.png": require("../assets/images/menkyogentsuki_1088.png"),
  "menkyogentsuki_1091.png": require("../assets/images/menkyogentsuki_1091.png"),
  "menkyogentsuki_1094.png": require("../assets/images/menkyogentsuki_1094.png"),
  "menkyogentsuki_1097.png": require("../assets/images/menkyogentsuki_1097.png"),
  "menkyogentsuki_1100.png": require("../assets/images/menkyogentsuki_1100.png"),
  "menkyogentsuki_1103.png": require("../assets/images/menkyogentsuki_1103.png"),
  "menkyogentsuki_1106.png": require("../assets/images/menkyogentsuki_1106.png"),
  "menkyogentsuki_1109.png": require("../assets/images/menkyogentsuki_1109.png"),
  "menkyogentsuki_1112.png": require("../assets/images/menkyogentsuki_1112.png"),
  "menkyogentsuki_1115.png": require("../assets/images/menkyogentsuki_1115.png"),
  "menkyogentsuki_1118.png": require("../assets/images/menkyogentsuki_1118.png"),
  "menkyogentsuki_1121.png": require("../assets/images/menkyogentsuki_1121.png"),
  "menkyogentsuki_1124.png": require("../assets/images/menkyogentsuki_1124.png"),
  "menkyogentsuki_1127.png": require("../assets/images/menkyogentsuki_1127.png"),
  "menkyogentsuki_113.png": require("../assets/images/menkyogentsuki_113.png"),
  "menkyogentsuki_1130.png": require("../assets/images/menkyogentsuki_1130.png"),
  "menkyogentsuki_1133.png": require("../assets/images/menkyogentsuki_1133.png"),
  "menkyogentsuki_1136.png": require("../assets/images/menkyogentsuki_1136.png"),
  "menkyogentsuki_1139.png": require("../assets/images/menkyogentsuki_1139.png"),
  "menkyogentsuki_1142.png": require("../assets/images/menkyogentsuki_1142.png"),
  "menkyogentsuki_1145.png": require("../assets/images/menkyogentsuki_1145.png"),
  "menkyogentsuki_1148.png": require("../assets/images/menkyogentsuki_1148.png"),
  "menkyogentsuki_1151.png": require("../assets/images/menkyogentsuki_1151.png"),
  "menkyogentsuki_1154.png": require("../assets/images/menkyogentsuki_1154.png"),
  "menkyogentsuki_1157.png": require("../assets/images/menkyogentsuki_1157.png"),
  "menkyogentsuki_116.png": require("../assets/images/menkyogentsuki_116.png"),
  "menkyogentsuki_1160.png": require("../assets/images/menkyogentsuki_1160.png"),
  "menkyogentsuki_1163.png": require("../assets/images/menkyogentsuki_1163.png"),
  "menkyogentsuki_1166.png": require("../assets/images/menkyogentsuki_1166.png"),
  "menkyogentsuki_1169.png": require("../assets/images/menkyogentsuki_1169.png"),
  "menkyogentsuki_1172.png": require("../assets/images/menkyogentsuki_1172.png"),
  "menkyogentsuki_1175.png": require("../assets/images/menkyogentsuki_1175.png"),
  "menkyogentsuki_1178.png": require("../assets/images/menkyogentsuki_1178.png"),
  "menkyogentsuki_1181.png": require("../assets/images/menkyogentsuki_1181.png"),
  "menkyogentsuki_1184.png": require("../assets/images/menkyogentsuki_1184.png"),
  "menkyogentsuki_1187.png": require("../assets/images/menkyogentsuki_1187.png"),
  "menkyogentsuki_119.png": require("../assets/images/menkyogentsuki_119.png"),
  "menkyogentsuki_1190.png": require("../assets/images/menkyogentsuki_1190.png"),
  "menkyogentsuki_1193.png": require("../assets/images/menkyogentsuki_1193.png"),
  "menkyogentsuki_1196.png": require("../assets/images/menkyogentsuki_1196.png"),
  "menkyogentsuki_1199.png": require("../assets/images/menkyogentsuki_1199.png"),
  "menkyogentsuki_1202.png": require("../assets/images/menkyogentsuki_1202.png"),
  "menkyogentsuki_1205.png": require("../assets/images/menkyogentsuki_1205.png"),
  "menkyogentsuki_1208.png": require("../assets/images/menkyogentsuki_1208.png"),
  "menkyogentsuki_123.png": require("../assets/images/menkyogentsuki_123.png"),
  "menkyogentsuki_124.png": require("../assets/images/menkyogentsuki_124.png"),
  "menkyogentsuki_126.png": require("../assets/images/menkyogentsuki_126.png"),
  "menkyogentsuki_127.png": require("../assets/images/menkyogentsuki_127.png"),
  "menkyogentsuki_129.png": require("../assets/images/menkyogentsuki_129.png"),
  "menkyogentsuki_138.png": require("../assets/images/menkyogentsuki_138.png"),
  "menkyogentsuki_143.png": require("../assets/images/menkyogentsuki_143.png"),
  "menkyogentsuki_144.png": require("../assets/images/menkyogentsuki_144.png"),
  "menkyogentsuki_166.png": require("../assets/images/menkyogentsuki_166.png"),
  "menkyogentsuki_172.png": require("../assets/images/menkyogentsuki_172.png"),
  "menkyogentsuki_181.png": require("../assets/images/menkyogentsuki_181.png"),
  "menkyogentsuki_186.png": require("../assets/images/menkyogentsuki_186.png"),
  "menkyogentsuki_196.png": require("../assets/images/menkyogentsuki_196.png"),
  "menkyogentsuki_218.png": require("../assets/images/menkyogentsuki_218.png"),
  "menkyogentsuki_219.png": require("../assets/images/menkyogentsuki_219.png"),
  "menkyogentsuki_265.png": require("../assets/images/menkyogentsuki_265.png"),
  "menkyogentsuki_276.png": require("../assets/images/menkyogentsuki_276.png"),
  "menkyogentsuki_278.png": require("../assets/images/menkyogentsuki_278.png"),
  "menkyogentsuki_308.png": require("../assets/images/menkyogentsuki_308.png"),
  "menkyogentsuki_327.png": require("../assets/images/menkyogentsuki_327.png"),
  "menkyogentsuki_328.png": require("../assets/images/menkyogentsuki_328.png"),
  "menkyogentsuki_329.png": require("../assets/images/menkyogentsuki_329.png"),
  "menkyogentsuki_331.png": require("../assets/images/menkyogentsuki_331.png"),
  "menkyogentsuki_337.png": require("../assets/images/menkyogentsuki_337.png"),
  "menkyogentsuki_342.png": require("../assets/images/menkyogentsuki_342.png"),
  "menkyogentsuki_344.png": require("../assets/images/menkyogentsuki_344.png"),
  "menkyogentsuki_345.png": require("../assets/images/menkyogentsuki_345.png"),
  "menkyogentsuki_350.png": require("../assets/images/menkyogentsuki_350.png"),
  "menkyogentsuki_351.png": require("../assets/images/menkyogentsuki_351.png"),
  "menkyogentsuki_356.png": require("../assets/images/menkyogentsuki_356.png"),
  "menkyogentsuki_359.png": require("../assets/images/menkyogentsuki_359.png"),
  "menkyogentsuki_360.png": require("../assets/images/menkyogentsuki_360.png"),
  "menkyogentsuki_365.png": require("../assets/images/menkyogentsuki_365.png"),
  "menkyogentsuki_371.png": require("../assets/images/menkyogentsuki_371.png"),
  "menkyogentsuki_402.png": require("../assets/images/menkyogentsuki_402.png"),
  "menkyogentsuki_41.png": require("../assets/images/menkyogentsuki_41.png"),
  "menkyogentsuki_412.png": require("../assets/images/menkyogentsuki_412.png"),
  "menkyogentsuki_414.png": require("../assets/images/menkyogentsuki_414.png"),
  "menkyogentsuki_42.png": require("../assets/images/menkyogentsuki_42.png"),
  "menkyogentsuki_421.png": require("../assets/images/menkyogentsuki_421.png"),
  "menkyogentsuki_427.png": require("../assets/images/menkyogentsuki_427.png"),
  "menkyogentsuki_43.png": require("../assets/images/menkyogentsuki_43.png"),
  "menkyogentsuki_432.png": require("../assets/images/menkyogentsuki_432.png"),
  "menkyogentsuki_436.png": require("../assets/images/menkyogentsuki_436.png"),
  "menkyogentsuki_437.png": require("../assets/images/menkyogentsuki_437.png"),
  "menkyogentsuki_44.png": require("../assets/images/menkyogentsuki_44.png"),
  "menkyogentsuki_442.png": require("../assets/images/menkyogentsuki_442.png"),
  "menkyogentsuki_445.png": require("../assets/images/menkyogentsuki_445.png"),
  "menkyogentsuki_449.png": require("../assets/images/menkyogentsuki_449.png"),
  "menkyogentsuki_45.png": require("../assets/images/menkyogentsuki_45.png"),
  "menkyogentsuki_451.png": require("../assets/images/menkyogentsuki_451.png"),
  "menkyogentsuki_453.png": require("../assets/images/menkyogentsuki_453.png"),
  "menkyogentsuki_456.png": require("../assets/images/menkyogentsuki_456.png"),
  "menkyogentsuki_467.png": require("../assets/images/menkyogentsuki_467.png"),
  "menkyogentsuki_47.png": require("../assets/images/menkyogentsuki_47.png"),
  "menkyogentsuki_470.png": require("../assets/images/menkyogentsuki_470.png"),
  "menkyogentsuki_473.png": require("../assets/images/menkyogentsuki_473.png"),
  "menkyogentsuki_48.png": require("../assets/images/menkyogentsuki_48.png"),
  "menkyogentsuki_483.png": require("../assets/images/menkyogentsuki_483.png"),
  "menkyogentsuki_487.png": require("../assets/images/menkyogentsuki_487.png"),
  "menkyogentsuki_49.png": require("../assets/images/menkyogentsuki_49.png"),
  "menkyogentsuki_491.png": require("../assets/images/menkyogentsuki_491.png"),
  "menkyogentsuki_495.png": require("../assets/images/menkyogentsuki_495.png"),
  "menkyogentsuki_50.png": require("../assets/images/menkyogentsuki_50.png"),
  "menkyogentsuki_504.png": require("../assets/images/menkyogentsuki_504.png"),
  "menkyogentsuki_505.png": require("../assets/images/menkyogentsuki_505.png"),
  "menkyogentsuki_51.png": require("../assets/images/menkyogentsuki_51.png"),
  "menkyogentsuki_511.png": require("../assets/images/menkyogentsuki_511.png"),
  "menkyogentsuki_512.png": require("../assets/images/menkyogentsuki_512.png"),
  "menkyogentsuki_52.png": require("../assets/images/menkyogentsuki_52.png"),
  "menkyogentsuki_520.png": require("../assets/images/menkyogentsuki_520.png"),
  "menkyogentsuki_521.png": require("../assets/images/menkyogentsuki_521.png"),
  "menkyogentsuki_522.png": require("../assets/images/menkyogentsuki_522.png"),
  "menkyogentsuki_527.png": require("../assets/images/menkyogentsuki_527.png"),
  "menkyogentsuki_53.png": require("../assets/images/menkyogentsuki_53.png"),
  "menkyogentsuki_533.png": require("../assets/images/menkyogentsuki_533.png"),
  "menkyogentsuki_535.png": require("../assets/images/menkyogentsuki_535.png"),
  "menkyogentsuki_536.png": require("../assets/images/menkyogentsuki_536.png"),
  "menkyogentsuki_54.png": require("../assets/images/menkyogentsuki_54.png"),
  "menkyogentsuki_547.png": require("../assets/images/menkyogentsuki_547.png"),
  "menkyogentsuki_55.png": require("../assets/images/menkyogentsuki_55.png"),
  "menkyogentsuki_553.png": require("../assets/images/menkyogentsuki_553.png"),
  "menkyogentsuki_554.png": require("../assets/images/menkyogentsuki_554.png"),
  "menkyogentsuki_555.png": require("../assets/images/menkyogentsuki_555.png"),
  "menkyogentsuki_561.png": require("../assets/images/menkyogentsuki_561.png"),
  "menkyogentsuki_565.png": require("../assets/images/menkyogentsuki_565.png"),
  "menkyogentsuki_568.png": require("../assets/images/menkyogentsuki_568.png"),
  "menkyogentsuki_589.png": require("../assets/images/menkyogentsuki_589.png"),
  "menkyogentsuki_600.png": require("../assets/images/menkyogentsuki_600.png"),
  "menkyogentsuki_604.png": require("../assets/images/menkyogentsuki_604.png"),
  "menkyogentsuki_613.png": require("../assets/images/menkyogentsuki_613.png"),
  "menkyogentsuki_621.png": require("../assets/images/menkyogentsuki_621.png"),
  "menkyogentsuki_630.png": require("../assets/images/menkyogentsuki_630.png"),
  "menkyogentsuki_631.png": require("../assets/images/menkyogentsuki_631.png"),
  "menkyogentsuki_633.png": require("../assets/images/menkyogentsuki_633.png"),
  "menkyogentsuki_641.png": require("../assets/images/menkyogentsuki_641.png"),
  "menkyogentsuki_653.png": require("../assets/images/menkyogentsuki_653.png"),
  "menkyogentsuki_655.png": require("../assets/images/menkyogentsuki_655.png"),
  "menkyogentsuki_668.png": require("../assets/images/menkyogentsuki_668.png"),
  "menkyogentsuki_674.png": require("../assets/images/menkyogentsuki_674.png"),
  "menkyogentsuki_675.png": require("../assets/images/menkyogentsuki_675.png"),
  "menkyogentsuki_678.png": require("../assets/images/menkyogentsuki_678.png"),
  "menkyogentsuki_681.png": require("../assets/images/menkyogentsuki_681.png"),
  "menkyogentsuki_683.png": require("../assets/images/menkyogentsuki_683.png"),
  "menkyogentsuki_688.png": require("../assets/images/menkyogentsuki_688.png"),
  "menkyogentsuki_689.png": require("../assets/images/menkyogentsuki_689.png"),
  "menkyogentsuki_690.png": require("../assets/images/menkyogentsuki_690.png"),
  "menkyogentsuki_708.png": require("../assets/images/menkyogentsuki_708.png"),
  "menkyogentsuki_715.png": require("../assets/images/menkyogentsuki_715.png"),
  "menkyogentsuki_717.png": require("../assets/images/menkyogentsuki_717.png"),
  "menkyogentsuki_720.png": require("../assets/images/menkyogentsuki_720.png"),
  "menkyogentsuki_722.png": require("../assets/images/menkyogentsuki_722.png"),
  "menkyogentsuki_736.png": require("../assets/images/menkyogentsuki_736.png"),
  "menkyogentsuki_746.png": require("../assets/images/menkyogentsuki_746.png"),
  "menkyogentsuki_753.png": require("../assets/images/menkyogentsuki_753.png"),
  "menkyogentsuki_754.png": require("../assets/images/menkyogentsuki_754.png"),
  "menkyogentsuki_756.png": require("../assets/images/menkyogentsuki_756.png"),
  "menkyogentsuki_758.png": require("../assets/images/menkyogentsuki_758.png"),
  "menkyogentsuki_761.png": require("../assets/images/menkyogentsuki_761.png"),
  "menkyogentsuki_783.png": require("../assets/images/menkyogentsuki_783.png"),
  "menkyogentsuki_784.png": require("../assets/images/menkyogentsuki_784.png"),
  "menkyogentsuki_802.png": require("../assets/images/menkyogentsuki_802.png"),
  "menkyogentsuki_803.png": require("../assets/images/menkyogentsuki_803.png"),
  "menkyogentsuki_805.png": require("../assets/images/menkyogentsuki_805.png"),
  "menkyogentsuki_807.png": require("../assets/images/menkyogentsuki_807.png"),
  "menkyogentsuki_810.png": require("../assets/images/menkyogentsuki_810.png"),
  "menkyogentsuki_812.png": require("../assets/images/menkyogentsuki_812.png"),
  "menkyogentsuki_824.png": require("../assets/images/menkyogentsuki_824.png"),
  "menkyogentsuki_827.png": require("../assets/images/menkyogentsuki_827.png"),
  "menkyogentsuki_828.png": require("../assets/images/menkyogentsuki_828.png"),
  "menkyogentsuki_830.png": require("../assets/images/menkyogentsuki_830.png"),
  "menkyogentsuki_84.png": require("../assets/images/menkyogentsuki_84.png"),
  "menkyogentsuki_841.png": require("../assets/images/menkyogentsuki_841.png"),
  "menkyogentsuki_842.png": require("../assets/images/menkyogentsuki_842.png"),
  "menkyogentsuki_846.png": require("../assets/images/menkyogentsuki_846.png"),
  "menkyogentsuki_848.png": require("../assets/images/menkyogentsuki_848.png"),
  "menkyogentsuki_851.png": require("../assets/images/menkyogentsuki_851.png"),
  "menkyogentsuki_852.png": require("../assets/images/menkyogentsuki_852.png"),
  "menkyogentsuki_858.png": require("../assets/images/menkyogentsuki_858.png"),
  "menkyogentsuki_859.png": require("../assets/images/menkyogentsuki_859.png"),
  "menkyogentsuki_862.png": require("../assets/images/menkyogentsuki_862.png"),
  "menkyogentsuki_872.png": require("../assets/images/menkyogentsuki_872.png"),
  "menkyogentsuki_876.png": require("../assets/images/menkyogentsuki_876.png"),
  "menkyogentsuki_886.png": require("../assets/images/menkyogentsuki_886.png"),
  "menkyogentsuki_901.png": require("../assets/images/menkyogentsuki_901.png"),
  "menkyogentsuki_904.png": require("../assets/images/menkyogentsuki_904.png"),
  "menkyogentsuki_909.png": require("../assets/images/menkyogentsuki_909.png"),
  "menkyogentsuki_910.png": require("../assets/images/menkyogentsuki_910.png"),
  "menkyogentsuki_918.png": require("../assets/images/menkyogentsuki_918.png"),
  "menkyogentsuki_919.png": require("../assets/images/menkyogentsuki_919.png"),
  "menkyogentsuki_920.png": require("../assets/images/menkyogentsuki_920.png"),
  "menkyogentsuki_926.png": require("../assets/images/menkyogentsuki_926.png"),
  "menkyogentsuki_935.png": require("../assets/images/menkyogentsuki_935.png"),
  "menkyogentsuki_956.png": require("../assets/images/menkyogentsuki_956.png"),
  "menkyogentsuki_960.png": require("../assets/images/menkyogentsuki_960.png"),
  "menkyogentsuki_962.png": require("../assets/images/menkyogentsuki_962.png"),
  "menkyogentsuki_965.png": require("../assets/images/menkyogentsuki_965.png"),
  "menkyogentsuki_975.png": require("../assets/images/menkyogentsuki_975.png"),
  "menkyogentsuki_986.png": require("../assets/images/menkyogentsuki_986.png"),
};

function resolveSrc(name: string | undefined) {
  if (!name) return null;
  return imageMap[name] ?? null;
}

export function IllustrationImage({
  file,
  style,
  imageStyle,
}: IllustrationImageProps) {
  const src = resolveSrc(file);

  if (!src) {
    return (
      <View style={[styles.placeholder, style as object]}>
        <Text style={styles.placeholderText}>HV</Text>
      </View>
    );
  }

  return (
    <View style={[styles.container, style as object]}>
      <Image
        source={src}
        style={[styles.image, imageStyle as object]}
        resizeMode="contain"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    overflow: "hidden",
    backgroundColor:"rgba(255, 255, 255, 0)",
    alignItems: "center",
    justifyContent: "center",
  },
  placeholder: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e5e5e5",
  },
  placeholderText: {
    fontSize: 10,
    color: "#a3a3a3",
  },
  image: {
    width: "100%",
    height: "100%",
    maxWidth: "100%",
    maxHeight: "100%",
  },
});
